apiVersion: v1
kind: Service
metadata:
  name: library-be-service
spec:
  type: LoadBalancer
  selector:
    app: library-be
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
      #nodePort: 30000

  