apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-fe
  template:
    metadata:
      labels:
        app: library-fe
    spec:
      containers:
      - name: library-fe
        image: library/library-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
