apiVersion: v1
kind: Service
metadata:
  name: library-fe-service
spec:
  selector:
    app.kubernetes.io/name: library-fe-deployment
  ports:
    - protocol: TCP
      port: 3000  # Port, pod którym będzie dostępna aplikacja na zewnątrz
      targetPort: 3000  # Port, na którym aplikacja działa wewnątrz kontenera
  type: LoadBalancer